import NextTopLoader from 'nextjs-toploader';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Cairo,Changa } from "next/font/google"

const cairo = Cairo({ subsets: ['arabic'], variable: '--font-cairo' });
const changa = Changa({ subsets: ['arabic'], variable: '--font-changa' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${cairo.variable} ${changa.variable}`}
      >
        <Toaster />
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
